### ISSUE TITLE
Not Working in IOS 16.0

### ISSUE THREAD

**Issue by piyush2greedy** [tradle/react-native-udp#222]
After updating my phone to ios 16.0. Not able to get local devices in the network. 
There are no devices coming after the ios 16.0 update.

In previous versions, it was working fine.

This is breaking production. Can someone please look into it?

@mvayngrib @fnando @aprock @Rapsssito @eliaslecomte 
Please help.

**Comment by evan1715** [comment]
sadly, it's Apple being Apple.
from what i've read, in iOS 16, they've "enforced" (their fancy word for 'fixed a bug') something they've written back in iOS 14.5. it requires their 'multicast entitlement.' you must request the permission from Apple. we've submitted our request today and i am hoping that this will fix the issue. it's possible that this package or other things must be done still, but i do not know at the moment.

this potentially means that all previous versions of anyone's app will now be broken on iOS 16 without a patch if they require UDP to function. i doubt they back track this permission and blanket all previous versions with it since once this permission is granted, it must be signed through xcode.

sources:
-> [user post](https://developer.apple.com/forums/thread/714211) 
--> [same forum FAQ](https://developer.apple.com/forums/thread/663875)
-> [network multicast entitlement](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_networking_multicast)
--> [request permission from Apple itself](https://developer.apple.com/contact/request/networking-multicast)

**Comment by hubciorz** [comment]
@evan1715 I am not sure. The source of the problem is somewhere else I think. We do have the multicast entitlement and UDP stops working after a certain amount of time. Killing the app does not help. Rebooting the phone helps. I have no idea what's wrong.

Did you receive the entitlement and it helped?

**Comment by hubciorz** [comment]
@evan1715 Any news? We did not really get any response from Apple. One day the entitlement was just available to be enabled in developer.apple.com.

**Comment by evan1715** [comment]
@hubciorz Got the entitlement. Same way you got it, without an acknowledgement that they did it. I'm not seeing any major issues with UDP so far. 

On occasion, it will stop working or the bind function will throw an error, crashing it only on iOS (even though it's wrapped in try-catch) after a socket creation fails. When it does stop working (after sitting in the app with the screen on for at least 15 minutes), placing the app in the background then bringing it back to the foreground restores it. However, that is also after an unrealistic time frame of the app being open with the display remaining on.

These are only from my testing (except the bind issue) and I don't have any repeated customer complaints that I've heard of. Perhaps as time goes by, I will hear something, but at the moment, it seems ok.

**Comment by bartoszboruta** [comment]
Any updates?

**Comment by Alessio92** [comment]
Same issue here, our customers are reporting this behaviour..
Is there any workaround?

**Comment by mvayngrib** [comment]
sorry guys, i don't have the bandwidth to dig into this 😓
