### ISSUE TITLE
Broadcast to the whole network

### ISSUE THREAD

**Issue by tanerparcali** [tradle/react-native-udp#236]
Why can't I broadcast to '255.255.255.255' as a public broadcast? How can I make all devices listening on the network see the broadcast?

**Comment by gibo77** [comment]
255.255.255.255 is reserved from what I know. There is a range only. The devices should be programmed to be on UDP server. They will respond. The broadcaster is another thing you have to handle. Since all devices will reply you need to set a Promise and a timer in my case to capture each one of them and put them in an array of data. It ain't easy 
For beginners. Just like what they said, one step at a time and test test test. 
Sent from Yahoo Mail for iPhone


On Monday, December 26, 2022, 2:32 AM, tanerparcali ***@***.***> wrote:




Why can't I broadcast to '255.255.255.255' as a public broadcast? How can I make all devices listening on the network see the broadcast?

**Comment by tanerparcali** [comment]
My situation is exactly like this:

I have a queue build to capture devices.

- I have a device eg ip address 193.168.2.1
- I have three different devices on the same network with ip addresses 2 .. 3... 4.

- I set the first device with 193.168.2.1 as the udp server and configured it to broadcast 255.255.255.0.

- Devices with other 2 .. 3.. 4.. threads are in listener client mode.

My goal is to detect the device broadcasting to 255.255.255.0 by other devices. But I couldn't do it because when I use 255.255.255.0 to broadcast to the public network, the message seems to go away but no one can receive it.

However, when I broadcast directly from the first device to a ip adress by other devices, for example, to a device with a 2 end, the devices see each other.

*** So my main question is, which ip range I broadcast from the device set as a udp server, I will have the opportunity to send a signal that introduces myself to the whole network.

Thank you

**Comment by gibo77** [comment]
Try not using 225.255.255.0 first in broadcasting. According to Wkipeda use this ranges. 
IPv4 multicast addresses are defined by the most-significant bit pattern of 1110. This originates from the classful network design of the early Internet when this group of addresses was designated as Class D. The CIDR notation for this group is 224.0.0.0/4.[1] The group includes the addresses from 224.0.0.0 to 239.255.255.255. 
You have to be mindful on the port number as described. 
Also you need to set up UDP servers in each of the client devices. Mine are ESP8266 in Arduino using regular API they have. The program I have for tradle UDP in RN was used in a Promise and a counter that captures each of the clients response. Since i have an array, each counter will be saved in an array. A timer has to be involved for each counter because it is an Asynchronous event. It worked for me. 

Sent from Yahoo Mail for iPhone


On Saturday, December 31, 2022, 4:29 AM, tanerparcali ***@***.***> wrote:




My situation is exactly like this:

I have a queue build to capture devices.
   
   -    
I have a device eg ip address 193.168.2.1

   -    
I have three different devices on the same network with ip addresses 2 .. 3... 4.

   -    
I set the first device with 193.168.2.1 as the udp server and configured it to broadcast 255.255.255.0.

   -    
Devices with other 2 .. 3.. 4.. threads are in listener client mode.


My goal is to detect the device broadcasting to 255.255.255.0 by other devices. But I couldn't do it because when I use 255.255.255.0 to broadcast to the public network, the message seems to go away but no one can receive it.

However, when I broadcast directly from the first device to a ip adress by other devices, for example, to a device with a 2 end, the devices see each other.

*** So my main question is, which ip range I broadcast from the device set as a udp server, I will have the opportunity to send a signal that introduces myself to the whole network.

Thank you
