### ISSUE TITLE
setBroadcast(true) not working on Android

### ISSUE THREAD

**Issue by Rapsssito** [tradle/react-native-udp#96]
When calling **`socket.setBroadcast(true)`** on Android after binding the socket, it makes whole the process hang forever. This method works on iOS.

**Comment by luobao1207** [comment]
I have the same problem.

**Comment by luobao1207** [comment]
@Rapsssito Have you solved it?

**Comment by Rapsssito** [comment]
Sadly, no.

**Comment by luobao1207** [comment]
@Rapsssito  
I've been working all day, but I still haven't solved the problemwe. we need author's help. 
If you solve it, please let me know.thanks

**Comment by Rapsssito** [comment]
I think it is related to the Android part. It looks like the process hangs on setting the socket broadcast to `true`.

**Comment by Rapsssito** [comment]
There could be useful info in #82 and @shynst's commit in his fork: https://github.com/shynst/react-native-udp/commit/aef3f01981d3ed3358181a9e2f8763257b86000d.

**Comment by thibmaek** [comment]
I'm indeed seeing the hanging behaviour here. It even results in an error in a flow where you:

1. create a udpv4 socket
2. bind it
3. set broadcasting
4. call socket.close

That will throw an error `Socket is closed` from inside the `setBroadcast` method because it is still hanging.

Anyway, I've found that I can just omit the call to `setBroadcast` completely for Android. It nog longer produces the error or hangs the call (duh), but is still able to use UDP broadcasting just fine without it (Android 8, 9 and 10)

**Comment by Rapsssito** [comment]
Duplicate of #82, moving discussion over that issue.
